### ISSUE TITLE
sample is README is not working and can not work 

### ISSUE THREAD

**Issue by RoadRunnr** [nats-io/jetstream-gh-action#40]
Documentation is wrong and none of the samples can work like that.

The sample in the README suggest that you get a nats instance with working jetstream support by simply starting the nats image like that:

```
    services:
      # starts a JetStream service locally known as "jetstream" on the network
      jetstream:
        image: nats:latest
```

However, `nats:latest` (currently 2.10.21) does not enable jetstream by default. One would need to pass the "-js" option the nats-server, but there is no way to do that with a GitHub actions service.
